"""
contextual_retrieval.py — Contextual Retrieval enrichment for PediCompass.

Implements the Anthropic Contextual Retrieval technique:
  https://www.anthropic.com/news/contextual-retrieval

Each chunk is enriched by prepending a short (≤ 100 word) document-level
context generated by Claude Haiku. This context anchors the chunk within
the broader guideline, dramatically improving retrieval precision when a
user query doesn't happen to use the exact words that appear in the chunk.

Why Haiku (not Sonnet)?
- This step runs once at ingest time for every chunk in the corpus.
- Cost at Claude Haiku pricing is ~$1–2 for the full PediCompass KB.
- Sonnet would cost ~10× more for the same operation with no quality gain
  on a 100-word summarisation task.
- Model ID is read from BEDROCK_HAIKU_MODEL_ID env var so it can be
  updated without code changes when Haiku versions are released.

Failure handling:
- If a Bedrock call fails for a specific chunk, the original chunk text
  is returned unchanged and a WARNING is logged. The ingest job continues.
- A brief exponential-backoff retry (max 3 attempts) handles transient
  throttling.

Rate limiting:
- A configurable inter-request delay (default 0.5 s) prevents hitting
  Bedrock's TPS limits when processing large documents.
"""

import json
import logging
import os
import time
from typing import Optional

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

# ── Defaults (overridable via constructor args or env vars) ───────────────────

_DEFAULT_MAX_RETRIES: int = 3
_DEFAULT_RETRY_BASE_DELAY: float = 1.0   # seconds; doubles each retry
_DEFAULT_INTER_REQUEST_DELAY: float = 0.5  # seconds between Bedrock calls

# Haiku has a ~200k token context window; we send doc_summary + chunk.
# Cap the document summary at this many characters to avoid huge prompts.
_MAX_DOC_SUMMARY_CHARS: int = 4000
_MAX_CHUNK_CHARS: int = 2000  # Haiku's input is generous; cap for cost control


# ── Context prompt template ───────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are a medical document analysis assistant specializing in pediatric clinical guidelines.
Your task is to provide a concise contextual description of a text chunk within a larger guideline document.
Keep your response under 100 words. Be factual and specific. Do not add medical advice."""

_CONTEXT_PROMPT_TEMPLATE = """<document_summary>
{doc_summary}
</document_summary>

<chunk>
{chunk_text}
</chunk>

In 1–3 sentences, describe what section of the guideline this chunk belongs to and what specific \
pediatric topic or clinical situation it addresses. This description will be prepended to the chunk \
to improve search retrieval. Be concise and specific."""


# ── Implementation ────────────────────────────────────────────────────────────

class ContextualRetrieval:
    """
    Enriches text chunks with Bedrock-generated contextual descriptions.

    Usage::

        cr = ContextualRetrieval(doc_summary="NICE CG160 fever guideline...")
        enriched_chunks = cr.enrich_batch(chunks, show_progress=True)
    """

    def __init__(
        self,
        doc_summary: str,
        aws_region: Optional[str] = None,
        haiku_model_id: Optional[str] = None,
        max_retries: int = _DEFAULT_MAX_RETRIES,
        inter_request_delay: float = _DEFAULT_INTER_REQUEST_DELAY,
    ) -> None:
        """
        Args:
            doc_summary:          Short description of the source document (generated
                                  from the parsed document title + first section).
            aws_region:           AWS region for Bedrock. Defaults to AWS_REGION env var
                                  or 'ap-southeast-1'.
            haiku_model_id:       Bedrock inference profile ID for Claude Haiku.
                                  Defaults to BEDROCK_HAIKU_MODEL_ID env var.
            max_retries:          Number of retry attempts on throttle/transient errors.
            inter_request_delay:  Seconds to wait between consecutive Bedrock calls.
        """
        self._doc_summary = doc_summary[:_MAX_DOC_SUMMARY_CHARS]
        self._max_retries = max_retries
        self._inter_request_delay = inter_request_delay

        # Resolve model ID
        self._model_id = (
            haiku_model_id
            or os.environ.get("BEDROCK_HAIKU_MODEL_ID", "")
        )
        if not self._model_id:
            raise ValueError(
                "BEDROCK_HAIKU_MODEL_ID is not set. "
                "Run 'aws bedrock list-inference-profiles --region ap-southeast-1 | grep haiku' "
                "to find the correct inference profile ID and add it to your .env file."
            )

        # Build Bedrock client
        region = aws_region or os.environ.get("AWS_REGION", "ap-southeast-1")
        self._bedrock = boto3.client("bedrock-runtime", region_name=region)
        logger.info(
            "ContextualRetrieval initialised | model=%s region=%s",
            self._model_id,
            region,
        )

    # ── Public API ─────────────────────────────────────────────────────────

    def enrich(self, chunk_text: str) -> str:
        """
        Generate and prepend a contextual description to a single chunk.

        Args:
            chunk_text: The raw chunk text from the chunker.

        Returns:
            Enriched text with the contextual description prepended,
            or the original chunk_text if enrichment fails after retries.
        """
        context = self._generate_context(chunk_text)
        if context:
            return f"{context}\n\n{chunk_text}"
        # Fallback: return original text unchanged
        return chunk_text

    def enrich_batch(
        self,
        chunk_texts: list[str],
        show_progress: bool = True,
    ) -> list[str]:
        """
        Enrich a list of chunk texts. Applies rate-limit delay between calls.

        Args:
            chunk_texts:    List of raw chunk texts.
            show_progress:  Whether to display a tqdm progress bar.

        Returns:
            List of enriched texts (same length as input).
        """
        results: list[str] = []
        iterator = chunk_texts

        if show_progress:
            try:
                from tqdm import tqdm
                iterator = tqdm(
                    chunk_texts,
                    desc="Contextual Retrieval (Bedrock Haiku)",
                    unit="chunk",
                )
            except ImportError:
                logger.warning("tqdm not installed; no progress bar for contextual retrieval.")

        for i, text in enumerate(iterator):
            enriched = self.enrich(text)
            results.append(enriched)

            # Rate-limit delay (skip after last item)
            if i < len(chunk_texts) - 1:
                time.sleep(self._inter_request_delay)

        return results

    # ── Private helpers ────────────────────────────────────────────────────

    def _generate_context(self, chunk_text: str) -> Optional[str]:
        """
        Call Bedrock Claude Haiku to generate a contextual description.

        Returns the generated context string, or None on failure.
        """
        truncated_chunk = chunk_text[:_MAX_CHUNK_CHARS]
        prompt = _CONTEXT_PROMPT_TEMPLATE.format(
            doc_summary=self._doc_summary,
            chunk_text=truncated_chunk,
        )

        payload = {
            "anthropic_version": "bedrock-2023-05-31",
            "system": _SYSTEM_PROMPT,
            "messages": [
                {"role": "user", "content": prompt}
            ],
            "max_tokens": 150,   # 100-word description fits comfortably in 150 tokens
            "temperature": 0.0,  # Deterministic for consistency across re-runs
        }

        for attempt in range(1, self._max_retries + 1):
            try:
                response = self._bedrock.invoke_model(
                    modelId=self._model_id,
                    contentType="application/json",
                    accept="application/json",
                    body=json.dumps(payload),
                )
                body = json.loads(response["body"].read())
                content_blocks = body.get("content", [])
                if content_blocks and content_blocks[0].get("type") == "text":
                    context = content_blocks[0]["text"].strip()
                    logger.debug("Generated context (%d chars)", len(context))
                    return context

                logger.warning("Unexpected Bedrock response structure: %s", body)
                return None

            except ClientError as exc:
                error_code = exc.response["Error"]["Code"]
                if error_code in ("ThrottlingException", "ServiceUnavailableException"):
                    delay = _DEFAULT_RETRY_BASE_DELAY * (2 ** (attempt - 1))
                    logger.warning(
                        "Bedrock throttled (attempt %d/%d) — retrying in %.1fs",
                        attempt, self._max_retries, delay,
                    )
                    time.sleep(delay)
                    continue
                # Non-retryable error
                logger.warning(
                    "Bedrock ClientError [%s] for chunk — skipping enrichment: %s",
                    error_code, exc,
                )
                return None

            except Exception as exc:
                logger.warning(
                    "Unexpected error during contextual retrieval (attempt %d/%d): %s",
                    attempt, self._max_retries, exc,
                )
                if attempt < self._max_retries:
                    time.sleep(_DEFAULT_RETRY_BASE_DELAY * attempt)
                    continue
                return None

        logger.warning(
            "Exhausted %d retries for contextual retrieval — using original chunk",
            self._max_retries,
        )
        return None

    @staticmethod
    def build_doc_summary(title: str, first_section_text: str, source_authority: str) -> str:
        """
        Build a document-level summary string from parsed document metadata.

        This is passed to __init__ as `doc_summary` and used in every
        context generation prompt to anchor the chunk in the broader document.

        Args:
            title:              Document title extracted by the parser.
            first_section_text: Text of the first (non-table) section.
            source_authority:   e.g., "NICE", "WHO", "CDC", "AAP".

        Returns:
            A concise multi-sentence document description string.
        """
        # Truncate first section to ~500 chars for the summary
        intro = first_section_text[:500].strip()
        if len(first_section_text) > 500:
            intro += "..."

        return (
            f"Source: {source_authority} clinical guideline.\n"
            f"Document title: {title}\n"
            f"Introduction excerpt: {intro}"
        )
